[package]
name = "plugin_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

commy_macro = { path = "../../commy_macro" }
rkyv = "0.8"
rkyv_derive = "0.8"
commy = { path = "../../" }
once_cell = "1.18"


[profile.release]
opt-level = 3
