[package]
edition = "2021"
name = "commy_common"
version = "0.1.0"

[dependencies]
dashmap = { version = "6.0.1", features = ["inline", "rayon"] }
memmap2 = "0.9.4"
once_cell = "1.19.0"

[features]
default = []
