name: Auto Merge on Green
on:
  workflow_run:
    workflows: ["Continuous Integration", "Cap'n Proto Codegen", "FFI smoke test"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  merge-if-green:
    runs-on: ubuntu-latest
    steps:
      - id: check_event
        name: Check event payload
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
        run: |
          echo "Workflow run for PR concluded successfully. Attempting to merge..."
          PR_NUMBER=$(jq --raw-output '.workflow_run.pull_requests[0].number' < "$GITHUB_EVENT_PATH")
          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
            echo "No PR associated with workflow_run; exiting"
            exit 0
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
      - name: Merge pull request
        if: ${{ steps.check_event.outputs.PR_NUMBER != '' }}
        env:
          PR_NUMBER: ${{ steps.check_event.outputs.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Merging PR #${PR_NUMBER} via REST API"
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
            -X PUT "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge" \
            -d '{"merge_method":"squash"}')
          echo "Response: $RESPONSE"
