name: Cap'n Proto Codegen CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-capnp:
    name: Build with capnp codegen
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Install Rust
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
          profile: minimal

      - name: Install capnp compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y capnproto

      - name: Install capnpc plugin
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo install capnpc --locked || (echo "cargo install capnpc failed" && echo "PATH=$PATH" && exit 1)
          echo "PATH=$HOME/.cargo/bin:$PATH"

      - name: Show Cap'n Proto tooling
        run: |
          echo "PATH=$PATH"
          capnp --version || (echo 'capnp not found' && exit 1)
          # Detect capnpc binary; if it exists but crashes, continue so the
          # subsequent build step runs with RUST_BACKTRACE=1 to capture full
          # diagnostic information.
          if command -v capnpc >/dev/null 2>&1; then
            if ! capnpc --version >/dev/null 2>&1; then
              echo "capnpc present but failed to print version; continuing for diagnostics"
            else
              capnpc --version
            fi
          elif command -v capnpc-rust >/dev/null 2>&1; then
            if ! capnpc-rust --version >/dev/null 2>&1; then
              echo "capnpc-rust present but failed to print version; continuing for diagnostics"
            else
              capnpc-rust --version
            fi
          elif command -v capnpc-rust-bootstrap >/dev/null 2>&1; then
            if ! capnpc-rust-bootstrap --version >/dev/null 2>&1; then
              echo "capnpc-rust-bootstrap present but failed to print version; continuing for diagnostics"
            else
              capnpc-rust-bootstrap --version
            fi
          else
            echo 'capnpc not found' && exit 1
          fi

      - name: Build (capnproto feature)
        run: |
          cargo build -p commy --features capnproto --verbose

      - name: Run tests (capnproto feature)
        run: |
          cargo test -p commy --features capnproto --verbose
