name: Cap'n Proto CI (consolidated)
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  capnp:
    name: Cap'n Proto (matrix)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Set up Rust
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Cap'n Proto (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y capnproto

      - name: Install Cap'n Proto (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          # Homebrew formula is 'capnp' (not capnproto)
          brew install capnp

      - name: Install Cap'n Proto (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Chocolatey package is 'capnproto'
          choco install -y capnproto

      - name: Install capnpc plugin (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          # Try a single install; if it fails, print PATH and exit so CI surfaces the error
          cargo install capnpc --locked || (echo "cargo install capnpc failed" && echo "PATH=$PATH" && exit 1)
          echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - name: Install capnpc plugin (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $env:Path = "$env:USERPROFILE\\.cargo\\bin;" + $env:Path
          cargo install capnpc --locked
          Add-Content -Path $env:GITHUB_ENV -Value "PATH=$env:USERPROFILE\\.cargo\\bin;$env:PATH"

      - name: Show Cap'n Proto tooling
        shell: bash
        run: |
          echo "PATH=$PATH"
          capnp --version || (echo 'capnp not found' && exit 1)
          # capnpc can be installed under several executable names (capnpc, capnpc-rust, capnpc-rust-bootstrap)
          if command -v capnpc >/dev/null 2>&1; then
            capnpc --version
          elif command -v capnpc-rust >/dev/null 2>&1; then
            capnpc-rust --version
          elif command -v capnpc-rust-bootstrap >/dev/null 2>&1; then
            capnpc-rust-bootstrap --version
          else
            echo 'capnpc not found' && exit 1
          fi
          echo "capnpc:" $(command -v capnpc || command -v capnpc-rust || command -v capnpc-rust-bootstrap || echo "not found")
        if: runner.os != 'Windows'

      - name: Show Cap'n Proto tooling (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "PATH=$env:Path"
          try { & capnp --version } catch { Write-Host 'capnp not found'; exit 1 }
          # Check multiple possible capnpc executable names created by cargo install and older installers
          $candidates = @(
            "$env:USERPROFILE\\.cargo\\bin\\capnpc.exe",
            "$env:USERPROFILE\\.cargo\\bin\\capnpc-rust.exe",
            "$env:USERPROFILE\\.cargo\\bin\\capnpc-rust-bootstrap.exe",
            "$env:ProgramFiles\\capnproto\\bin\\capnpc.exe",
            "$env:ProgramFiles(x86)\\capnproto\\bin\\capnpc.exe"
          )
          $found = $false
          foreach ($p in $candidates) {
            if (Test-Path $p) { & $p --version; $found = $true; break }
          }
          if (-not $found) { Write-Host 'capnpc not found'; exit 1 }

      - name: Build (capnproto feature)
        run: |
          cargo build -p commy --features capnproto --verbose

      - name: Run tests (capnproto feature)
        run: |
          cargo test -p commy --features capnproto --verbose

      # Run the focused single-step smoke test on Ubuntu to keep matrix runs fast.
      - name: Run single-step capnp smoke test (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cargo test --features capnproto --test smoke_capnp_single_step --verbose
        env:
          RUSTFLAGS: "-D warnings"
