name: Cap'n Proto single-step smoke
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  capnp-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Install capnp
        run: |
          sudo apt-get update -y
          sudo apt-get install -y capnproto
      - name: Install Rust
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build and run smoke test (capnproto)
        run: |
          # Run only the smoke test that verifies single-step capnp codegen.
          cargo test --features capnproto --test smoke_capnp_single_step --verbose
        env:
          RUSTFLAGS: "-D warnings"
