name: Cap'n Proto Codegen CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-capnp:
    name: Build with capnp codegen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install capnp compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y capnproto

      - name: Build (capnproto feature)
        run: |
          cargo build -p commy --features capnproto --verbose

      - name: Run tests (capnproto feature)
        run: |
          cargo test -p commy --features capnproto --verbose
