name: Continuous Integration

on:
  push:
    branches: [ main, ci/pin-capnp-workflows ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test-rust:
    name: Test Core (Rust)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --workspace --features "all_formats" --verbose

      - name: Run tests
        run: cargo test --workspace --features "all_formats" --verbose

      - name: Upload capnpc diagnostics (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: capnpc-diagnostics-${{ matrix.os }}
          path: |
            **/capnpc_diagnostics/**
          if-no-files-found: ignore

  test-sdks:
    name: Test SDKs (placeholder)
    runs-on: ubuntu-latest
    needs: test-rust

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python SDK tests (Placeholder)
        run: |
          echo ">>> Running Python SDK tests..."
          # cd sdks/python
          # pip install -r requirements.txt
          # pytest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run Node.js SDK tests (Placeholder)
        run: |
          echo ">>> Running Node.js SDK tests..."
          # cd sdks/nodejs
          # npm install
          # npm test
